name: Notify about new build

on:
  push:
    tags:
      - '*'
  release:
    types: [published, created]
  workflow_dispatch:

env:
  SLACK_AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}

jobs:
  sendMessage:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        # env:
        #   BUILD_URL: ${{ steps.gcloud.outputs.url }}
        #   BRANCH_NAME: ${{ steps.branch-detect.outputs.name }}
        run: |
          # git fetch --all
          # BASE_BRANCH=${GITHUB_BASE_REF:-master}
          # BASE_REF="remotes/origin/${BASE_BRANCH}"
          # commitMessage=$(git log $BASE_REF..HEAD --skip 1 --pretty=format:%B)
          # message="branch: $BRANCH_NAME"
          buildUrl="https://github.com/zeriontech/zerion-wallet-extension/archive/refs/tags/${GITHUB_REF}.zip"
          message="New wallet extension build! ${buildUrl}"
          # message+='\ndeployed to: '"$BUILD_URL"
          # message+='\n'"${commitMessage}"
          # message=${message//\"/\\\"} # escape double quotes
          # json='{"text":"'$message'", "icon_emoji": ":gift:", "channel": "C01HR720Q7K"}'
          json='{"text":"'$message'", "icon_emoji": ":gift:", "channel": "G017MDDTZGD"}'
          curl https://slack.com/api/chat.postMessage \
            -X POST \
            -H 'Content-type: application/json' \
            -H "Authorization: Bearer $SLACK_AUTH_TOKEN" \
            --data "$json"
